#!/bin/bash

# NOTE: This script assumes a newly-generated `target` folder was generated by Terraform and either:
#  1) Copied over by the TF script and invoked by remote-exec, or
#  2) Manually copied over by the user and manually invoked.

# Purge EC2 of pre-existing files prior to unpacking /target.
HOME_PATH=/home/ec2-user

rm -rf $HOME_PATH/tower.env || true
rm -rf $HOME_PATH/tower.yml || true
rm -rf $HOME_PATH/docker-compose.yml || true
rm -rf $HOME_PATH/data-studios.env || true
rm -rf $HOME_PATH/data-studios-rsa.pem || true


# Populate the ~/.bashrc with values the Ansible scripts need.
{
  echo -e "\n\n# CONFIG ADDED BY TERRAFORM INSTALLER ON: $(date)"
  echo -e "export APP_NAME=${app_name}"
  echo -e "export CACERT_DO_NOT_USE_HTTPS=${flag_do_not_use_https}"

  echo -e "export DB_POPULATE_EXTERNAL_INSTANCE=${populate_external_db}"
  echo -e "export DB_URL=\"${tower_db_url}\""

  echo -e "export WAVE_LITE_ACTIVATED=${use_wave_lite}"

  echo -e "export TOWER_SERVER_URL=${tower_server_url}"
  echo -e "export TOWER_API_ENDPOINT=${tower_api_endpoint}"
  echo -e "export SEQERAKIT_USE_HOSTS_FILE=${flag_create_hosts_file_entry}"
} >> ~/.bashrc


# If R53 record not created, point tower_base_url to 127.0.0.1 so seqerakit can still run with the DNS name.
# Populate hosts file if necessary. Must use sudo.
%{ if flag_create_hosts_file_entry == true }
  echo -e "127.0.0.1 ${tower_base_url}" | sudo tee -a /etc/hosts > /dev/null
%{ endif }
