/*
## ------------------------------------------------------------------------------------
## Mandatory Bootstrap Values
## ------------------------------------------------------------------------------------
This is the most critical configuration section.

If you intend to run multiple instances in the same account, you MUST ensure that each
implementation has its own unique `app_name`. This name is used as a namespace isolator
in the AWS SSM prefix and ensures the right configuration is pulled for the right stack.

Once you have created the omnibus secret objects in SSM (see `templates/ssm_*` files),
supply these values to the `secrets_bootstrap_*` parameters. During the deployment, these
objects will be retrieved and created as individual key-value pairs in the SSM (in a way
that makes the values available to the Tower instance via its native SSM integration).

`aws_*` values are required to ensure Terraform is acting against the correct AWS target.
Client authentication regimes can vary (static keys, role assumption, credential process,
etc) and it is impossible to accommodate all scenarios OOTB. The values supplied here are
used to configure the `aws provider` in `000-main.tf`. Adjust if necessary.

`tower_container_version` identifies the proprietary Seqera containers your Seqera Platform
will use. While it is possible to bump/drop versions and successfully redeploy, be mindful
that each version has its expectations re: configuration settings and database migration.
Before changing this value, consider backing up your database and consulting Seqera Platform
Release Notes (https://docs.seqera.io/platform/latest/enterprise/release_notes/enterprise_latest)
for any notable breaking change.
*/

# Use hyphen as separator or else some AWS resource nameing breaks (e.g. ALB)
app_name = "tower-template"

secrets_bootstrap_tower       = "/seqera/sensitive-values/tower-template/tower"
secrets_bootstrap_seqerakit   = "/seqera/sensitive-values/tower-template/seqerakit"
secrets_bootstrap_groundswell = "/seqera/sensitive-values/tower-template/groundswell"
secrets_bootstrap_wave_lite   = "/seqera/sensitive-values/tower-template/wave-lite"


aws_account = "REPLACE_ME"
aws_region  = "REPLACE_ME"
aws_profile = "REPLACE_ME"

# TODO(#435): switch to the v26.2.0 GA tag once it is published.
tower_container_version = "v26.2.0-RC16"


/*
## ------------------------------------------------------------------------------------
## SSM
## ------------------------------------------------------------------------------------
Activate this setting to allow n+1 deployments to overwrite SSM keys if they were not
generated by your own Terraform project (can be useful to set this to true if running 2+
instances off of the same configuration, otherwise you will get errors at the end of the
`apply` cycle.

Note!
 - 1) Terraform will show a deprecation warning -- there is no better option than this
 however, so we continue to use this option for now).
 - 2) Setting this value to `false` will not prevent overrwrites if SSM entries are
  tracked within your own project state.
*/
flag_overwrite_ssm_keys = true


/*
## ------------------------------------------------------------------------------------
## Tags -- Default
## ------------------------------------------------------------------------------------
Default tags to put on every generated resource.
*/
default_tags = {
  Terraform   = "true"
  Environment = "dev"
}


/*
## ------------------------------------------------------------------------------------
## Flags - Custom Naming
## ------------------------------------------------------------------------------------
Use these settings to forgo the default `tf-RANDOM-NAME-` resource name prefix.
Do not include hyphen at end (unless you want a double hyphen in the resulting name).
Use hyphen as separator.
*/
flag_use_custom_resource_naming_prefix = false
custom_resource_naming_prefix          = "REPLACE_ME_IF_NECESSARY"


/*
## ------------------------------------------------------------------------------------
## Flags - Infrastructure
## ------------------------------------------------------------------------------------
These flags control what infrastructure will be created new versus what already-in-place
assets can be leveraged. The flags set here will require further changes in the sections below
(example: `flag_create_new_vpc = true` will require you to make decisions about subnets and CIDRs
in `VPC (New)` section).

Related flags are grouped into a logical block. Only 1 entry in each block should be true.

We generally suggest clients deploy into a new VPC when possible. This minimizes blast-radius in the
event of an error and allows you to focus on the stack itself rather than having to troubleshoot unexpected
behaviours due to other assets in your pre-existing VPC. Once you are happy things are working properly,
you can start to introduce pre-existing assets.

New VPC deployments may sometimes be inappropriate for your business reality (i.e. you have highly customized
networking / firewall rules / restrictive policies on access to core services like email and DNS. In such cases,
deploying into an existing VPC should be the preferred option.

Load-balancing can prove to be tricky due to its implications on networking and TLS certificates, and behaviour
assumptions we have made while building the tool. Please note:

  - If you want to use an ALB in your solution, it will be net new (we do not support using an existing instance).
  - If you use an ALB in your solution, it MUST serve a TLS certifcate stored in the AWS Certificate Manager.
  - If you need TLS but don't want an ALB, we supply a custom docker-compose file running an nginx reverse-proxy
    which can be loaded up with a CA certificate and key (we suggest using the ALB whenever possible, however).
      - This solution supports the use of pre-existing certificates & the creation of a brand new self-signed CA.
      - This flow has not been extensively tested and is commended only for highly specific circumstances.
  - Although *highly* unadvised (given the relative ease with which a TLS cert can be provisioned these days),
    you may also choose to run your instance in HTTP-only mode. Choosing this option will result in the addition of
    the `TOWER_ENABLE_UNSAFE_MODE = TRUE` config setting to your Seqera Platform instance.
*/

# Only one of these can true.
flag_create_new_vpc   = true
flag_use_existing_vpc = false

# Only one of these can be true.
# NOTE: If using pre-existing RDS instance, ensure it accepts traffic from whole VPC on 3306.
flag_create_external_db       = false
flag_use_existing_external_db = false
flag_use_container_db         = true

# Only one of these can be true.
# NOTE: Redis version/port for the container deployment are hard-coded in docker-compose.yaml.
#  External (ElastiCache) deployments are configurable via the `platform_redis_elasticache` block below.
flag_create_external_redis = false
flag_use_container_redis   = true

# Only one of these can true.
# NOTE: If using `flag_use_private_cacert = true` flag, read Custom Private CA section for full instructions on private cert set-up.
flag_create_load_balancer = true
flag_use_private_cacert   = false
flag_do_not_use_https     = false


/*
## ------------------------------------------------------------------------------------
## Flags - Networking
## ------------------------------------------------------------------------------------
Your Seqera Platform instance needs to be reachable via http/https (for your users), and
via SSH (administrators/installer). Depending on users and corporate policies, your Tower
instance may need to be directly accessible via the public internet, or locked to a limited
subset of internal traffic only.

If you choose to make your instance public, it will reside in a public subnet with a public IP.
You can still place a load-balancer in front of the application, but SSH will occur by direclty
calling the VM on port 22.

If you choose to make your Tower private, SSH networking becomes more difficult. By default, an
AWS Instance Connect Endpoint will be created and associated with the private subnet where your
Tower instance resides. Access is controlled via a combination of SSH key and IAM permissions.
This solution is good for green-field deployments into relatively open AWS accounts.

If you make your Tower fully private, please note:

  1. The instance must still be capable of egressing to the public internet (i.e. NAT). If you
     choose to create a new VPC, be advised that opinionated NAT-related decisions are hardcoded
    into the `001-vpc.tf` file.

  2. Making your instance fully private can cause downstream complications in the event your
     compute environments reside in another AWS Account / cloud (the Nextflow head job needs to
     be able to establish a connection back to the Tower instance).

If deploying into an existing VPC with bespoke networking, the EICE may be inappropriate. In such
cases - if private networking already exists between your workstation and the VPC into which Tower
is being installed, choose the `flag_private_tower_without_eice` option. This causes the generated
ssh_config file to be populated with the VM's private IP, with any SSH connection being sent to the VM
directly.

The remaining entries in this section are present because they are affected by networking accessibility
decisions:

  - You can tell the installer to stop as soon as infrastructure is provisioned and
    the `assets/target` folder has been created. We don't advise setting this to false, but it is available
    in the event your networking restrictions are so tight that a real-time SSH connection simply isn't possible.

  - The custom docker-compose file is partially affected by the TLS flag decision in the previous section but
    also because the `assets/customcerts/custom_default.conf` file may need to be adjusted.

  - Setting the Wave flag to true means the Wave Service will be available to your instance, but also relies on
    the ability for the Seqera Platform instance to successfully establish a Websockets connection to the
    `wave.seqera.io` endpoint.
*/

# Only one of these can true.
# flag_make_instance_private or flag_private_tower_without_eice = true makes ALB internal-facing
# flag_make_instance_private_behind_public_alb = true makes ALB internet-facing
flag_make_instance_public                    = false
flag_make_instance_private                   = false
flag_make_instance_private_behind_public_alb = true
flag_private_tower_without_eice              = false

# Manage how to talk to VM for config file transfer.
flag_vm_copy_files_to_instance = true


/*
## ------------------------------------------------------------------------------------
## Wave Service
## ------------------------------------------------------------------------------------
Enable Tower to connect to the Wave service.

To connect the Seqera-hosted Wave Service, set `flag_use_wave` to true.
To connect to a self-hosted Wave Lite instance instead, set `flag_use_wave_lite` to true.

Seqera-hosted wave is reached at "wave.seqera.io" Wave-Lite is a domain defined by you.  Do not add `https://` for either one.

If you are deploying a Wave-LIte instance, you will need to make a decision re: DNS. Seqera recommends exposing
the service as a subdomain of your `tower_server_url` value (see entry in section further below). This pattern works
well because you can reuse this pattern if/when you enable the Studios feature. e.g:
    - wave.myseqeraplatform.example.com

If you organization cannot support subdomains, you will need to deply a peer record so that DNS population logic continues
to work. e.g:
    - myseqeraplatform.example.com
    - mywavelite.example.com

*/
flag_use_wave               = false
flag_use_wave_lite          = false
wave_lite_container_version = "v1.38.0"

num_wave_lite_replicas = 2
wave_server_url        = "wave.seqera.io"

/*
## ------------------------------------------------------------------------------------
## Flags - DNS
## ------------------------------------------------------------------------------------
DNS regimes can vary and the installer tries its best to be flexible. Several options are
available if you are able to limit the generation of A records within the AWS Account where
your Seqera Platform instance resides. If this is not possible, a workaround will be used
where the value of the TOWER_SERVER_URL value is written into the VM's `etc/hosts`
file to support short-term installer needs while you update your external DNS independently
(remember to remove the `/etc/hosts` entry once this offline process is complete!).

In our experience, clients have found it handy to purchase a domain within the AWS Account
where the Seqera Platform instance will run. This allows the project team to quickly make
updates when necessary and avoid a dependency on potentially slower-moving elements in their
organization. The downside, however, is that this introduces shadow IT into the organization.
Choose the option that is appropriate for you.
*/

# Only one can be true
flag_create_route53_private_zone       = true
flag_use_existing_route53_public_zone  = false
flag_use_existing_route53_private_zone = false
flag_create_hosts_file_entry           = false

# Populate this field if creating a new private hosted zone
new_route53_private_zone_name = "REPLACE_ME_IF_NEEDED"

# Only populate if flag set above to use existing hosted zone.
existing_route53_public_zone_name  = "REPLACE_ME_IF_NEEDED"
existing_route53_private_zone_name = "REPLACE_ME_IF_NEEDED"


/*
## ------------------------------------------------------------------------------------
## Custom Private CA
## ------------------------------------------------------------------------------------
Do not use this option unless absolutely necessary. In general, your pipeline maintenance
obligations will be easier if you use a public certificate (e.g. issued by AWS) on an ALB.
See: https://docs.seqera.io/platform/latest/enterprise/configuration/ssl_tls

If you choose to generate a new private CA, please following the instructions in
`documentation/setup/optional_private_certificates.md`
*/

# Include s3:// and omit trailing slash
private_cacert_bucket_prefix = "REPLACE_ME_IF_NEEDED"

# Make Platform and Studios trust your private root CA (rootCA.crt in the bucket above, PEM-encoded).
# Requires: flag_use_private_cacert = true, tower_container_version >= v26.2.0,
# data_studio_container_version >= 0.12.2, and Studio images built on Connect 0.13.0+
# (checked by `make verify`; older images only get a warning).
flag_run_studios_via_private_ca = false


/*
## ------------------------------------------------------------------------------------
## VPC (New)
## ------------------------------------------------------------------------------------
Values here are placeholders only. Replace as necessary.
NOTES:
  - Ensure the region specified in `vpc_new_az` matches the region at top of file.
  - You must always have at least one public subnet (for NAT egress).
  - You must have at least 2 public subnets if using an internet-facing ALB.
  - There must only be a single EC2 subnet (to align with EICE quota limitations)
*/

vpc_new_cidr_range = "10.0.0.0/16"
vpc_new_azs        = ["REPLACE_ME_IF_NEEDED-1a", "REPLACE_ME_IF_NEEDED-1b"]

vpc_new_public_subnets  = ["10.0.1.0/24", "10.0.2.0/24"]
vpc_new_private_subnets = ["10.0.3.0/24", "10.0.4.0/24", "10.0.5.0/24", "10.0.6.0/24"]

# Ensure these subnet ranges align to what's created above.
vpc_new_ec2_subnets   = ["10.0.3.0/24"] # Can only 1 for EICE to work.
vpc_new_batch_subnets = ["10.0.3.0/24"]
vpc_new_db_subnets    = ["10.0.3.0/24", "10.0.4.0/24"]
vpc_new_redis_subnets = ["10.0.5.0/24"]

# Must be >= 2, in different AZs. Ensure only public subnets (nothing needs to be in these).
vpc_new_alb_subnets = ["10.0.1.0/24", "10.0.2.0/24"]

# Specify is VPC flow logs should be enabled or not. Have cost implication.
enable_vpc_flow_logs = false

# Control whether a public IPv4 address should be assigned to instances spun up in the VPC subnets.
# There is an hourly cost for each IP, so this is default to false. However, if you place AWS Batch
# instances in a public subnet and dont assign a public IP, those machines will fail due join the ECS
# cluster due to a failure to downloaded assets from the public internet during boot.
# WARNING: If you enable this, consider making your ingress CIDR ranges more restrictive.
flag_map_public_ip_on_launch = false


/*
## ------------------------------------------------------------------------------------
## VPC (Existing)
## - If using existing IP, ensure ec2 subnet has public IP via auto-assignment (current as of Nov 16/23).
## ------------------------------------------------------------------------------------
Values here are placeholders only. Replace as necessary.
NOTES:
  - Ensure your private subnets have egress rights to the internet via NAT.
  - If your VM is in a public subnet, ensure the subnet auto-assigns a public IP.
  - You must have at least 2 public subnets if using an internet-facing ALB.
  - There must only be a single EC2 subnet (to align with EICE quota limitations)
*/

vpc_existing_id            = "REPLACE_ME_IF_NEEDED"
vpc_existing_ec2_subnets   = ["10.0.1.0/24"]
vpc_existing_batch_subnets = ["10.0.2.0/24", "10.0.3.0/24"]
vpc_existing_db_subnets    = ["10.0.4.0/24", "10.0.5.0/24"]
vpc_existing_redis_subnets = ["10.0.6.0/24"]

# Must be >= 2, in different AZs. Ensure only public subnets (nothing needs to be in these).
vpc_existing_alb_subnets = ["10.0.1.0/24", "10.0.2.0/24"]

/*
## ------------------------------------------------------------------------------------
## VPC Endpoints
## ------------------------------------------------------------------------------------
All endpoint options can be found here: https://docs.aws.amazon.com/vpc/latest/privatelink/aws-services-privatelink-support.html
Only include the service-specific portion of the name.
Eg. For EC2, use "ec2" rather than `com.amazonaws.region.ec2`
*/
vpc_gateway_endpoints_all = ["s3"]

vpc_interface_endpoints_tower = []
vpc_interface_endpoints_batch = []


/*
## ------------------------------------------------------------------------------------
## Security Group - Transaction Sources
## ------------------------------------------------------------------------------------
These settings control which IPs are allowed to call the VM / ALB. For ease of initial setup
these are *very* loose. Consider tightening if your deployment model allows it. The arrays can
contain multiple entries if necessary (e.g. you might wish to both your VPN CIDR and home IP to
be able to make HTTPS calls / SSH connections).

If using EICE, please note that individuals must have IAM rights to interact with the endpoint
prior to any SSH transaction being allowed against the VM.

Egress is open by default given variability of client implementations. Can be tightened if need be.
See: https://github.com/terraform-aws-modules/terraform-aws-security-group/blob/master/rules.tf
*/

sg_ingress_cidrs = ["0.0.0.0/0"]
sg_ssh_cidrs     = ["0.0.0.0/0"]

# CIDRs allowed to reach Studios SSH (port 2222). Governs the NLB's own security group.
# Studios SSH is NLB-only: flag_enable_data_studio_ssh = true requires
# flag_create_load_balancer = true. Must be non-empty when Studios SSH is enabled
# (validated at plan time by check_configuration.py).
sg_studio_ssh_cidrs = ["0.0.0.0/0"]

sg_egress_eice               = ["all-all"]
sg_egress_tower_ec2          = ["all-all"]
sg_egress_tower_alb          = ["all-all"]
sg_egress_batch_ec2          = ["all-all"]
sg_egress_interface_endpoint = ["all-all"]

/*
## ------------------------------------------------------------------------------------
## Groundswell
## ------------------------------------------------------------------------------------
Enable to allow pipeline optimization.
*/

flag_enable_groundswell = true

# Minimum 0.4.15: earlier images cannot connect to a MySQL DB that requires TLS.
swell_container_version = "0.4.15"
swell_database_name     = "swell"
## swell_db_user                        = "DO_NOT_UNCOMMENT_ME"
## swell_db_password                    = "DO_NOT_UNCOMMENT_ME"


/*
## ------------------------------------------------------------------------------------
## Data Explorer - Feature Gated (23.4.3+)
## ------------------------------------------------------------------------------------
Enable to allow Data Explorer functionality. See https://docs.seqera.io/platform/latest/data/data-explorer for details.
*/
flag_data_explorer_enabled        = true
data_explorer_disabled_workspaces = ""


/*
## ------------------------------------------------------------------------------------
## Data Studio - Feature Gated (24.1.0+)
## ------------------------------------------------------------------------------------
Enable to allow Data Studio functionality. Note, this requires several modifications to your instance.
Please check Release Notes and documentation to ensure this its your regulatory compliance needs.

NOTES:

1. If upgrading from a pre-24.1 installation, it is likely the existing certificate arn
  provided to the `alb_certificate_arn` entry needs to be replaced with a new cert with more entries.

2. If path-based routing (available as of v25.2.0), your ensure you certificate supports the domain
  specified in `data_studio_path_routing_url`.

3. The `data_studio_path_routing_url` should be a **bare domain** — do not include
   protocol prefixes like `https://` or path components. Example: `autoconnect.autodc.dev-seqera.net`

4. Studios:
    All workspaces:       flag_limit_data_studio_to_some_workspaces = false
    Specific workspaces:  flag_limit_data_studio_to_some_workspaces = true
                                                +
                          data_studio_eligible_workspaces = "12,34,56"

  SSH:
    All workspaces:       flag_limit_data_studio_ssh_to_some_workspaces = false
    Specific workspaces:  flag_limit_data_studio_ssh_to_some_workspaces = true
                                                +
                          data_studio_ssh_eligible_workspaces = "12,34,56"
  Note: Must use numeric id of target workspaces when populating `data_studio_eligible_workspaces`.
*/

# Studios
flag_enable_data_studio                   = true
data_studio_container_version             = "0.14.0"
flag_limit_data_studio_to_some_workspaces = false
data_studio_eligible_workspaces           = ""

# Studios SSH
flag_enable_data_studio_ssh                   = false
flag_limit_data_studio_ssh_to_some_workspaces = false
data_studio_ssh_eligible_workspaces           = ""

flag_studio_enable_path_routing = false
data_studio_path_routing_url    = "REPLACE_ME_IF_NECESSARY"

# NOTE: In addition to the Studios and Connect proxy variables below, there are additional optional variables that are intentionally omitted from this installer.
# See Design Decisions #20 and #21 in documentation/design_decisions.md for the full list and rationale.

# Studios - General behaviour (v26.1.0+)
data_studio_default_lifespan   = "8"   # default lifespan in hours per Studio
flag_studio_private_by_default = false # make Studios private by default

# Studios - Metrics (v26.1.0+)
data_studio_metrics_eligible_workspaces = "" # comma-separated workspace IDs; empty = all

# Studios - Wave integration (v26.1.0+)
# Requires flag_use_wave = true.
data_studio_wave_disallowed_registries   = "community.wave.seqera.io" # registries blocked as Wave build destinations
data_studio_wave_custom_image_registry   = ""                         # leave empty to use Wave default
data_studio_wave_custom_image_repository = ""                         # leave empty to use Wave default (data-studios/<tool>)

# Connect proxy - server config (v0.11.0+)
connect_management_port     = ""      # port for metrics/readiness endpoints; leave empty to disable
connect_management_auth_key = ""      # auth key for management endpoints; leave empty if not using management port
connect_log_level           = "debug" # logging verbosity (debug, info, warn, error)



# For full list of images Seqera makes available, please see: https://public.cr.seqera.io/
# NOTE!!
#  1. Current as of v24.1.x, only images from publicly-available repositories can be used.
#     Private repositories will be supported in a future iteration.
#  2. `qualifier` values MUST use hyphens (`-`), NOT underscores (`_`).
#  3. Versioning Strategy (See Design Decisions for more details.)
#     - Major and minor versions are pinned explicitly (e.g., `1.101.2-0.9.0` and `1.101.2-0.11.0`).
#     - Auto-use latest update by by omitting the patch (e.g. "1.101.2-0.9" instead of "1.101.2-0.9.0").
#   4. For the use of custom data studio images, ensure flag_use_wave = true.
#   5. Acceptable status values are: "recommended", "deprecated", and "experimental". Anything else will be displayed as "unsupported".
#   6. Current as of Platform v25.2.0, only VSCode, Jupyter, and R will work with path-based Studio routing (not Xpra). This must also be the 0.8.5 client version.
#   7. Newer VSCode images ship with Docker-in-Docker. This will break AWS Batch CEs using stock AL2 AMIs.
#        Ref: https://github.com/seqeralabs/studio-vscode/blob/vscode/1.101.2/connect/0.12.0/.seqera/Dockerfile#L93

data_studio_options = {
  # DEPENDENCY
  # DEPRECATION NOTICE (Sept 28/26): Connect-client v0.11.0 entries removed in 1.9.0. Future versions will not list entries for v0.12.2.
  # (July 31/25) - `rstudio-...` removed due to license issues.

  vscode-1-101-2-0-12-2 = {
    qualifier = "VSCODE-1-101-2-0-12-2"
    icon      = "vscode"
    tool      = "vscode"
    status    = "deprecated"
    container = "public.cr.seqera.io/platform/data-studio-vscode:1.101.2-0.12.2"
  },
  jupyter-4-2-5-0-12-2 = {
    qualifier = "JUPYTER-4-2-5-0-12-2"
    icon      = "jupyter"
    tool      = "jupyter"
    status    = "deprecated"
    container = "public.cr.seqera.io/platform/data-studio-jupyter:4.2.5-0.12.2"
  },
  ride-2025-04-1-0-12-2 = {
    qualifier = "RIDE-2025-04-1-0-12-2"
    icon      = "rstudio"
    tool      = "rstudio"
    status    = "deprecated"
    container = "public.cr.seqera.io/platform/data-studio-ride:2025.04.1-0.12.2"
  },
  xpra-6-2-0-R2-1-0-12-2 = {
    qualifier = "XPRA-6-2-0-R2-1-0-12-2"
    icon      = "xpra"
    tool      = "xpra"
    status    = "deprecated"
    container = "public.cr.seqera.io/platform/data-studio-xpra:6.2.0-r2-1-0.12.2"
  },
  vscode-1-105-1-0-14-0 = {
    qualifier = "VSCODE-1-105-1-0-14-0"
    icon      = "vscode"
    tool      = "vscode"
    status    = "recommended"
    container = "public.cr.seqera.io/platform/data-studio-vscode:1.105.1-0.14.0"
  },
  jupyter-4-6-0-0-14-0 = {
    qualifier = "JUPYTER-4-6-0-0-14-0"
    icon      = "jupyter"
    tool      = "jupyter"
    status    = "recommended"
    container = "public.cr.seqera.io/platform/data-studio-jupyter:4.6.0-0.14.0"
  },
  ride-2026-01-2-0-14-0 = {
    qualifier = "RIDE-2026-01-2-0-14-0"
    icon      = "rstudio"
    tool      = "rstudio"
    status    = "recommended"
    container = "public.cr.seqera.io/platform/data-studio-ride:2026.01.2-0.14.0"
  },
  xpra-6-3-6-R0-1-0-14-0 = {
    qualifier = "XPRA-6-3-6-R0-1-0-14-0"
    icon      = "xpra"
    tool      = "xpra"
    status    = "recommended"
    container = "public.cr.seqera.io/platform/data-studio-xpra:6.3.6-r0-1-0.14.0"
  }
}


/*
## ------------------------------------------------------------------------------------
## Data Lineage - Feature Gated (v26.1.0+)
## ------------------------------------------------------------------------------------
Enable Nextflow data lineage tracking. Records the provenance of pipeline runs at
workflow, task, and file levels.

Currently a public-preview feature; requires Platform v26.1.0+ and Nextflow v25.04+
(v26.04+ recommended).

PLATFORM v26.2.0+:
  - AWS SNS pushes lineage events to Platform over public HTTPS. `make verify` fails if
    the site is private, uses HTTP or a private CA, or has private-only DNS.
  - An unset TOWER_LINEAGE_ALLOWED_WORKSPACES now means "all workspaces". When
    `flag_enable_data_lineage = false`, the installer sets it to `-1` to keep lineage off.
  - Before v26.2.0, only `allowed_workspaces` is used.

data_lineage_options (tower.env variable in brackets):
  allowed_workspaces     "" = all workspaces; "12,34,56" = only those. (TOWER_LINEAGE_ALLOWED_WORKSPACES)
  store_prefix           Name prefix of the buckets and SNS topics Platform creates;
                         also limits the IAM policy.                   (TOWER_LINEAGE_STORE_PREFIX)
  sns_max_retries        SNS delivery retries.                         (TOWER_LINEAGE_SNS_MAX_RETRIES)
  sns_max_delay_seconds  Longest wait between SNS retries.             (TOWER_LINEAGE_SNS_MAX_DELAY_SECONDS)
  migrate_sqs_transport  One-off move of v26.1 SQS workspaces to SNS.  (TOWER_LINEAGE_MIGRATE_SQS_TRANSPORT)
  global_search_enabled  Global search.                                (TOWER_GLOBAL_SEARCH_ENABLED)

When enabled, the EC2 instance role gains permissions to create/manage S3 buckets
and SQS queues with the `seqera-lineage-*` prefix and, on v26.2.0+, S3 buckets and SNS
topics with the `store_prefix` prefix, so Platform can auto-provision per-workspace
lineage infrastructure.

See: https://docs.seqera.io/platform-enterprise/data/data-lineage
*/
flag_enable_data_lineage = false
data_lineage_options = {
  allowed_workspaces    = ""
  store_prefix          = "seqera-lineage"
  sns_max_retries       = 17
  sns_max_delay_seconds = 300
  migrate_sqs_transport = true
  global_search_enabled = true
}


/*
## ------------------------------------------------------------------------------------
## Database (Generic)
## Values that apply to both the containerized and RDS DBs
## ------------------------------------------------------------------------------------
## db_root_user                         = "DO_NOT_UNCOMMENT_ME"
## db_root_password                     = "DO_NOT_UNCOMMENT_ME"
## tower_db_user                        = "DO_NOT_UNCOMMENT_ME"
## tower_db_password                    = "DO_NOT_UNCOMMENT_ME"

WARNING:
  - If you create a database as part of your deployment, it will be destroyed on teardown.
  - You must supply your own backup solution.
*/

db_database_name = "tower"


/*
## ------------------------------------------------------------------------------------
## Database (Container)
## Specify the details of the external database to create (if applicable)
## ------------------------------------------------------------------------------------
This section added to handle new connection string requirements for Tower v24.1.0+
*/
db_container_engine = "mysql"
# Platform v26.1+ supports only MySQL 8.4. Upgrading an existing 8.0 container DB changes its data
# files one way, so back them up first: see documentation/setup/upgrade_mysql_8_4.md.
db_container_engine_version = "8.4"

/*
## ------------------------------------------------------------------------------------
## Database (External)
## ------------------------------------------------------------------------------------
The official Seqera reference architecture advises using an RDS instance as your Seqera
Platform's database. As of May 21/25 this section is augmented with settings for the
Wave-Lite feature (Release > 1.5.0).

You may choose to forgo this in lower environments if you are cost-conscious. Additionally,
when conducting initial interative testing, you may wish to stick with the containerized
database option as this avoids ~8 minutes of waiting for the RDS instance to instantiate
during each deployment cycle.

Commented out settings with value "DO_NOT_UNCOMMENT_ME" exist solely as visual reminder that
these settings are being used, but the value is coming from the SSM secret source.

WARNING:
  - If you create a database as part of your deployment, it will be destroyed on teardown.
  - You must supply your own backup solution.
*/

db_engine = "mysql"
# Platform v26.1+ supports only MySQL 8.4. Use major.minor ("8.4"), not a patch version, so
# automatic minor upgrades don't show as Terraform drift. db_param_group must match: "mysql8.4".
# To upgrade an existing 8.0 instance in place, follow documentation/setup/upgrade_mysql_8_4.md.
db_engine_version    = "8.4"
db_param_group       = "mysql8.4"
db_instance_class    = "db.m5.large"
db_allocated_storage = 30

db_deletion_protection = true
skip_final_snapshot    = false

# TLS (MySQL 8.4+ only; ignored on 8.0). When true, Platform connects with TLS (encrypted; the
# server certificate isn't verified), and an installer-created RDS instance or container DB
# refuses plaintext connections. Also applies to the container DB (db_container_engine_version).
db_enforce_tls = true

# 8.0 -> 8.4 upgrade switches. Set both true only for the upgrade apply, then back to false.
db_allow_major_version_upgrade = false
db_apply_immediately           = false

db_backup_retention_period  = 7
db_enable_storage_encrypted = true


wave_lite_db_engine = "postgres"
# TODO(#332): confirm the wave-lite Postgres engine version paired with the v26.1.x release set.
wave_lite_db_engine_version    = "17.5"
wave_lite_db_param_group       = "postgres17"
wave_lite_db_instance_class    = "db.t4g.micro" #"db.m5.large"
wave_lite_db_allocated_storage = 10

wave_lite_db_deletion_protection      = false
wave_lite_skip_final_snapshot         = true
wave_lite_db_backup_retention_period  = 7
wave_lite_db_enable_storage_encrypted = true


/*
## ------------------------------------------------------------------------------------
## Elasticache (External)
## Specify the details of the external database to create or reuse
## ------------------------------------------------------------------------------------
This is a compound object designed to facilated passing of values to the underlying
Elasticache module.

The module supports both singleton (unclustered) and clusterd mode.
Unclustered & clustered modes are mutually exclusive; if the `unclustered` block's
`num_cache_nodes` is non-zero, the `clustered` block must keep its null values.
*/

# Standalone Seqera Platform ElastiCache (Redis) cluster settings.
# Only consumed when `flag_create_external_redis = true`.
platform_redis_elasticache = {
  node_type       = "cache.m4.xlarge"
  num_cache_nodes = 1
  engine_version  = "7.0"
  port            = 6379
}

wave_lite_elasticache = {
  apply_immediately = true

  engine         = "redis"
  engine_version = "7.1"
  node_type      = "cache.t4g.micro"
  port           = 6379

  security_group_ids = [] # Leave blank to use TF-generated SG.
  subnet_ids         = [] # Leave blank to use all private subnets.

  unclustered = {
    num_cache_nodes = 1
  }

  clustered = {
    multi_az_enabled           = false
    automatic_failover_enabled = false
    num_node_groups            = null
    replicas_per_node_group    = null
    parameter_group_name       = "default.redis7"
  }

  encryption = {
    at_rest_encryption_enabled = true
    transit_encryption_enabled = true
    #kms_key_id missing
  }
}


/*
## ------------------------------------------------------------------------------------
## IAM
## ------------------------------------------------------------------------------------
By default, the installer will create an IAM Instance Role for the Seqera Platform VM.

In the event that your AWS Account is locked down and access to IAM is restricted, you
may override this process and supply a pre-generated entity.

NOTE: Remember that this is an INSTANCE role arn, not a normal Role.
*/

flag_iam_use_prexisting_role_arn = false
iam_prexisting_instance_role_arn = "REPLACE_ME_IF_NEEDED"


/*
## ------------------------------------------------------------------------------------
## SMTP
## ------------------------------------------------------------------------------------
Newer instances of Tower support native integration with SES, which foregoes long-lived
access keys in favour of an SES IAM permissions attached to the VM Instance Role. This is
the default option given the streamlined security gain.

If you do not wish to use SES integration, you can set this to false but will need to
uncomment and populate the `tower_smtp_user` and `tower_smtp_password` values in the TOWER
CONFIGURATION section below.
*/

# Only one of these can true.
flag_use_aws_ses_iam_integration = true
flag_use_existing_smtp           = false


/*
## ------------------------------------------------------------------------------------
## EC2 Host
## ------------------------------------------------------------------------------------
We generally advise implementing EBS encryption at an AWS Account level, but provide options
for a target encryption of the Seqera Platform VM only.

Some Amazon Linux 2023 AMIs (e.g. minimal) changed default boot size in late 2024. Starting
disk size can now be explicitly specified (in GiB).
*/

ec2_host_instance_type = "c5.2xlarge"

flag_encrypt_ebs     = true
flag_use_kms_key     = true
ec2_ebs_kms_key      = "REPLACE_ME_IF_NEEDED"
ec2_root_volume_size = 16

ec2_require_imds_token = true

ec2_update_ami_if_available = true


/*
## ------------------------------------------------------------------------------------
## ALB
## ------------------------------------------------------------------------------------
This must be a TLS certificate stored in the Amazon Certificate Manager.

If you have an already-issued cert from a public CA, consider storing it in ACM and using
an ALB to serve or else you will need to use the custom docker-compose file option with
a local nginx container acting as the TLS termination point.

NOTE: If upgrading from a pre-24.1 installation, it is likely the existing certificate arn
provided must be replaced with a new cert with more entries.
Please see https://docs.seqera.io for specific Data Studio cert guidance.
*/

alb_certificate_arn = "REPLACE_ME_IF_NEEDED"


/*
## ------------------------------------------------------------------------------------
## TOWER CONFIGURATION
## ------------------------------------------------------------------------------------
Please consult https://docs.seqera.io/platform/latest/enterprise/configuration/overview for
detailed configuration guidance.
*/

# Ensure this aligns with the values specified in `Flags - DNS` section above.
# Do not include http prefix. e.g. `autodc.dev-seqera.net`.
tower_server_url = "REPLACE_ME"

# This must be a verified identity / domain.
tower_contact_email = "REPLACE_ME"

# See full list of compute environment options at: https://docs.seqera.io/platform-enterprise/latest/enterprise/configuration/overview#compute-environments
tower_enable_platforms = "awsbatch-platform,k8s-platform,slurm-platform"

## tower_jwt_secret                      = "DO_NOT_UNCOMMENT_ME"
## tower_crypto_secretkey                = "DO_NOT_UNCOMMENT_ME"
## tower_license                         = "DO_NOT_UNCOMMENT_ME"

# Do not include 'jdbc:mysql://`.
# NOTE!
#  - If using container db: use `db:3306`
#  - If using pre-existing external RDS instance, include the RDS Endpoint string only (no port or /xxx... URI modifier)
#  - If a new RDS is created as part of this deployment, any populated string is acceptable
#    (this variable isn't used by cant be omitted).
#  - A pre-existing external DB must be Amazon RDS. With db_enforce_tls = true, use the RDS endpoint name
#    (ending in .rds.amazonaws.com), not a CNAME or alias. Platform and Groundswell verify the certificate.
tower_db_url           = "db:3306"
tower_db_driver        = "org.mariadb.jdbc.Driver"
tower_db_dialect       = "io.seqera.util.MySQL55DialectCollateBin"
tower_db_min_pool_size = 5
tower_db_max_pool_size = 10
tower_db_max_lifetime  = 18000000
## tower_db_user                         = "DO_NOT_UNCOMMENT_ME"
## tower_db_password                     = "DO_NOT_UNCOMMENT_ME"

## tower_redis_url                       = "DO_NOT_UNCOMMENT_ME"
## tower_redis_password                  = "DO_NOT_UNCOMMENT_ME"

tower_smtp_host = "REPLACE_ME"
tower_smtp_port = "REPLACE_ME"
## tower_smtp_user                      = "REPLACE_ME_IF_NEEDED"
## tower_smtp_password                  = "REPLACE_ME_IF_NEEDED"

tower_smtp_auth              = true
tower_smtp_starttls_enable   = true
tower_smtp_starttls_required = true
tower_smtp_ssl_protocols     = "TLSv1.2"

tower_root_users          = "REPLACE_ME"
tower_email_trusted_orgs  = "REPLACE_ME"
tower_email_trusted_users = "REPLACE_ME"

# Controls whether Seqera Platform will auto-create an underlying User entity when an
# unknown email is added directly to a resource.
#
#   - `flag_tower_enable_participant_auto_create_user` governs Workspace **collaborators**
#     (`tower.participant.auto-create-user`). If `true`, the email does not need a
#     pre-existing Platform account; if `false`, the User must already exist.
#
#   - `flag_tower_enable_member_auto_create_user` governs Organization **members**
#     (`tower.member.auto-create-user`). If `true`, adding an unknown email as an
#     Organization User auto-generates the underlying Platform User; if `false`, the
#     User must already exist.
flag_tower_enable_participant_auto_create_user = false
flag_tower_enable_member_auto_create_user      = false

tower_audit_retention_days = 1095 # 3 years (value in days)

# Audit Log v2 (v26.1.0+)
# Bundled object configuring Platform's audit-log-v2 behaviour. The `cleanup` sub-object
# gates the scheduled purge job by its own flag — set `cleanup = { enabled = false }`
# to disable purging entirely.
#
# write_mode applies to Platform v26.1 only ("dual" or "v2"). From v26.2.0, Platform writes
# only to the v2 table and ignores this value. Existing v1 rows stay readable until
# tower_audit_retention_days removes them. Move any readers of the tw_audit_log table to
# the v2 schema before upgrading.
#
# See: https://docs.seqera.io/platform-enterprise/enterprise/configuration/overview
tower_audit_log_v2 = {
  write_mode              = "dual"
  csv_export_max_logs     = 500000
  pre_post_change_enabled = false
  cleanup = {
    enabled    = true
    interval   = "5m"
    delay      = "10s"
    chunk_size = 1000
  }
}

tower_workflow_cleanup_enabled = true # only applicable for AWS Batch

# Compute environment cleanup (v26.1.0+)
# Bundled object controlling the scheduled job that identifies and deletes compute
# environments stuck in CREATING or DELETING states. Only active on the cron service
# container. All sub-fields have sensible defaults and may be omitted.
#
# Fields:
#   - enabled                : run the cleanup job. Default false.
#   - delay                  : initial delay before the first run (duration). Default "1m".
#   - interval               : how often the job runs (duration). Default "1h".
#   - batch_size             : compute environments handled per pass. Default 10.
#   - time_offset            : skip envs younger than this (duration). Default "60s".
#   - stuck_creating_timeout : how long in CREATING before considered stuck. Default "1h".
#   - stuck_deleting_timeout : how long in DELETING before considered stuck. Default "1h".
#
# See: https://docs.seqera.io/platform-enterprise/enterprise/configuration/overview
tower_compute_env_cleanup = {
  enabled                = false
  delay                  = "1m"
  interval               = "1h"
  batch_size             = 10
  time_offset            = "60s"
  stuck_creating_timeout = "1h"
  stuck_deleting_timeout = "1h"
}

tower_enable_openapi = true

# Telemetry (v26.2.0+). One of: "standard" | "basic" | "air-gapped".
#   standard   : standard + basic telemetry is sent to Seqera.
#   basic      : only basic telemetry is sent.
#   air-gapped : standard telemetry only (basic off), plus usage metrics written to files on the
#                instance (/home/ec2-user/.tower/usage-metrics) every 24h and kept for 90 days.
# Note: in every mode, including air-gapped, Platform still attempts a call to the Seqera telemetry
# server. Without a route to it, the call fails and is logged; Platform keeps running.
# Air-gapped also sets LICENSE_SERVER_URL to "" and LICENSE_CERTS_AIRGAPPED_BUNDLE to
# /etc/seqera/license-bundle.pem. You must supply the bundle file.
flag_enable_standard_telemetry = "standard"

# telemetry_options (tower.env variable in brackets). Applies in every telemetry mode.
#   window_days           Telemetry window in days.                        (TOWER_TELEMETRY_WINDOW_DAYS)
#   file_collector_delay  Wait before the first usage-metrics collection    (TOWER_CRON_USAGE_METRICS_FILE_COLLECTOR_DELAY)
#                         after Platform starts. Later runs are every 24h.
telemetry_options = {
  window_days          = 7
  file_collector_delay = "5s"
}

# Preflight checks (v26.2.0+). When true, Platform runs preflight checks and validates
# credentials before launching a pipeline. Matches the upstream default.
flag_enable_preflight_checks = true

# Customer-managed KMS key for pipeline secrets (v26.2.0+). Encrypts the temporary AWS Secrets
# Manager secrets Platform creates for runs on AWS Batch and AWS Cloud compute environments.
# Leave empty to use the AWS-managed key. Use a key ARN or key ID; aliases are not accepted.
# Applies to every such compute environment without its own key (set per compute environment
# under Advanced options > Pipeline secrets KMS key), so only set it when they all share the
# key's account and region. The compute environment credentials need kms:GenerateDataKey and
# kms:Decrypt on the key, and the compute environment execution role needs kms:Decrypt.
tower_aws_secrets_kms_key_id = ""

# Actions (v26.2.0+). Platform 26.2 adds three Action triggers, and turns all three ON by
# default in every workspace, including personal workspaces:
#   bucket   = launch a pipeline when a marker file is created/deleted in an S3 data repository.
#              Needs flag_data_explorer_enabled = true, and Platform reachable from AWS over public
#              HTTPS with a publicly trusted certificate (so not private, HTTP-only or private-CA
#              installs). The data repository's credential needs s3:Get/PutBucketNotificationConfiguration
#              and sns:CreateTopic/SetTopicAttributes/Subscribe/DeleteTopic (not the EC2 instance role).
#   cron     = launch a pipeline on a schedule.
#   pipeline = launch a pipeline when a watched pipeline's run succeeds, fails or is cancelled.
#
# To turn a trigger on or off, set its *_allowed_workspaces value:
#   ""          on in every workspace (Platform default)
#   "-1"        off everywhere (no workspace has this ID; same off value as lineage and WIF)
#   "123,456"   on only in these numeric workspace IDs (`tw workspaces list`)
# Restricting a trigger pauses that trigger's existing Actions in the excluded workspaces.
# GitHub webhook and Tower launch hook Actions are not affected.
#
# Rate limit: an Action that fires trigger_rate_max_per_window times within trigger_rate_window
# is paused until someone resumes it. The values below are Platform's defaults.
tower_actions = {
  bucket_trigger_allowed_workspaces   = ""
  cron_trigger_allowed_workspaces     = ""
  pipeline_trigger_allowed_workspaces = ""
  trigger_rate_max_per_window         = 20
  trigger_rate_window                 = "1h"
}

# Workload identity federation (v26.2.0+). AWS and Google Cloud credentials can hold only a role ARN
# (AWS) or a service account and provider path (Google), instead of long-lived keys. Platform signs a
# short-lived token that AWS/Google STS exchange for temporary cloud credentials.
#   tower_identity_federation_enabled            false: off in every workspace (TOWER_IDENTITY_FEDERATION_ALLOWED_WORKSPACES=-1).
#   tower_identity_federation_allowed_workspaces  "" = all workspaces, or "123,456" = only these (used when enabled).
# Requirements when enabled:
#   - AWS/Google STS must reach ${tower_server_url}/api/.well-known/openid-configuration and jwks.json
#     over public HTTPS with a publicly trusted certificate (not private, HTTP-only, or private-CA installs).
#   - The cloud side (AWS IAM OIDC provider + role trust policy, or a Google workload identity pool) is
#     set up by you, not the installer. The issuer URL is ${tower_server_url}/api.
# WARNING: existing Google Cloud WIF credentials present new token subjects (platform, data, studio,
# workflow) in enabled workspaces. Bindings that match only the `workflow` subject stop working.
# See documentation/setup/optional_workload_identity_federation.md.
tower_identity_federation_enabled            = false
tower_identity_federation_allowed_workspaces = ""

# If enabled, set eligibility to "" for all workspaces, or "WSP1_ID,WSP2_ID,..."
tower_enable_pipeline_versioning        = false
pipeline_versioning_eligible_workspaces = ""


/*
## ------------------------------------------------------------------------------------
## TOWER CONFIGURATION - OIDC
## ------------------------------------------------------------------------------------
Enable these settings to activate the OIDC login flow on the Seqera Platform landing page.

Please note that you must supply your OIDC secrets in the `ssm_sensitive_values_tower.json`
and have a pre-configured OIDC IDP ready to accept requests.
*/

flag_oidc_use_generic = false
flag_oidc_use_google  = false
flag_oidc_use_github  = false

flag_disable_email_login = false


/*
# ------------------------------------------------------------------------------------
# TOWER CONFIGURATION - Credentials
# ------------------------------------------------------------------------------------
Setting this value to true will allow AWS-type credentials within Seqera Platform to be
created without needing to specifyc long-lived AWS User credentials.

Please see `documentation/setup/optional_allow_instance_credentials.md` for project details,
and `https://docs.seqera.io/platform-enterprise/enterprise/advanced-topics/use-iam-role#configure-seqera`
for official Seqera documentation.

WARNING!
1. If this is activated, you must ensure that the target Role is configured to allow assumption by the
EC2 Instance Role created by this deployment. See `documentation/setup/optional_allow_instance_credentials.md`.
2. As of August 29/25 (v1.6.2) the solution will only add permission to EC2 instance role to `sts:AssumeRole` the
TOWER_AWS_ROLE specified in the `seqerakit_secrets` object. Other Roles not supported.
*/
flag_allow_aws_instance_credentials = false


/*
## ------------------------------------------------------------------------------------
## EC2 - Docker Configuration
## ------------------------------------------------------------------------------------
# https://docs.docker.com/config/containers/logging/local/

CIDR Range -- docker's default CIDR ranges can often collide with CIDRs allocated to VPNs.
The generation of docker networks via docker-compose and cause VPN-based SSH access to
fail due to the sudden introduction of conflicting CIDR ranges. Please see
https://www.heuristic42.com/blog/59/on-docker-stealing-routes-and-breaking-the-internet for
more details.
*/

flag_docker_logging_local    = false
flag_docker_logging_journald = true
flag_docker_logging_jsonfile = false

docker_cidr_range = "172.80.0.0/16"


/*
## ------------------------------------------------------------------------------------
## seqerakit
## ------------------------------------------------------------------------------------
DEPRECATED as of Release 1.8 — Seqerakit components are no longer actively maintained and
will be replaced by the Seqera Terraform provider. See `README.md` → "Supported Versions
& Components". The SSM entry referenced by `secrets_bootstrap_seqerakit` (below) must
still be created — the installer reads its path at plan time — but its contents may be
placeholder values if you don't intend to run the seqerakit step
(`flag_run_seqerakit = false`).

This section is an optional post-configuration activity. Once infrastructure is provisioned
and the Seqera Platform instance is running, you can create a compute environment and execute
a small pipeline run to verify if the environment is properly configured.

WARNING:

  - Terraform state is NOT aware of activities taken within your Seqera Platform instance. If
    you create compute environments via Tower Forge, please remember to purge these instances
    prior to tearing down the Terraform project.
  - Please ensure the first entry of the `tower_root_users` field is added as a
    `seqerakit_team_members` entry -- this will ensure the seqerakit population calls can
    complete successfully.
*/

flag_run_seqerakit = false

seqerakit_org_name     = "SampleOrg"
seqerakit_org_fullname = "SampleOrgFullName"
seqerakit_org_url      = "https://www.example.com"

seqerakit_team_name    = "SampleTeam"
seqerakit_team_members = "REPLACE_ME,REPLACE_ME"

seqerakit_workspace_name     = "SampleWorkspace"
seqerakit_workspace_fullname = "SampleWorkspaceFullName"

seqerakit_compute_env_name   = "MyComputeEnvironment"
seqerakit_compute_env_region = "REPLACE_ME"

seqerakit_root_bucket = "s3://REPLACE_ME"
seqerakit_workdir     = "s3://REPLACE_ME"
seqerakit_outdir      = "s3://REPLACE_ME"

seqerakit_aws_use_fusion_v2 = true
seqerakit_aws_use_forge     = true
seqerakit_aws_use_batch     = true

seqerakit_aws_fusion_instances = "c6id,r6id,m6id"
seqerakit_aws_normal_instances = "optimal"

seqerakit_aws_manual_head_queue    = "REPLACE_ME_IF_NEEDED"
seqerakit_aws_manual_compute_queue = "REPLACE_ME_IF_NEEDED"


/*
## ------------------------------------------------------------------------------------
## Seqerakit - Credentials
## ------------------------------------------------------------------------------------
By default, Seqerakit expects GitHub, Docker, and AWS to be defined in the `ssm_sensitive_values_seqera.json`
secret object. These are not absolutely necessary for initial short-term testing (although useful) and can
therefore be deactivated if not supplied.
*/

seqerakit_flag_credential_create_aws        = true
seqerakit_flag_credential_create_github     = true
seqerakit_flag_credential_create_docker     = true
seqerakit_flag_credential_create_codecommit = false

seqerakit_flag_credential_use_aws_role           = true
seqerakit_flag_credential_use_codecommit_baseurl = true
