#!/usr/bin/env python3

import sys


# sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
sys.dont_write_bytecode = True
# This suppresses the stacktrace emitted when assertion errors are thrown. Users will still see the
# human-friendly message, but not the rest of the noise. We'll need to socialize that that need to
# search for the error message in this file to see what the offending values are.
# Longer-term we can consider externalizing errors to another file so that longer messages can be
# written and returned without cluttering up the evaluation logic.
sys.tracebacklimit = 0

from types import SimpleNamespace  # noqa: E402  (deliberately after sys flag setup above)

from utils.extractors import get_tfvars_as_json  # noqa: E402  (deliberately after sys flag setup above)
from utils.logger import logger  # noqa: E402  (deliberately after sys flag setup above)


## ------------------------------------------------------------------------------------
## NOTE: See comments in utils/helpers.py for reasons why we created our own hacky tfvars parser.
## ------------------------------------------------------------------------------------


## ------------------------------------------------------------------------------------
## HELPER FUNCTIONS
## ------------------------------------------------------------------------------------


## ------------------------------------------------------------------------------------
## MAIN
## ------------------------------------------------------------------------------------
if __name__ == "__main__":
    logger.info("")
    logger.info("Beginning tfvars configuration check.")

    # Generate dictionary from tfvars then convert to SimpleNamespace for cleaner dot-notation access.
    # Kept the two objects different for convenience when .keys() method is required.
    data_dictionary = get_tfvars_as_json()
    data = SimpleNamespace(**data_dictionary)

    # Check minimum container version
    if data.flag_create_external_db:
        logger.warning(
            "[REMINDER]: Database snapshots generated by RDS must be deleted by hand or else Terraform gets stuck."
        )

        if data.db_deletion_protection:
            raise AssertionError(
                " You have deletion protection on your RDS instance. "
                "Please update the resource to remove protection before running `terraform destroy`."
            )

        if not data.skip_final_snapshot:
            raise AssertionError(
                " You will create a final snapshot of your RDS instance. "
                "Please disable snapshotting before running `terraform destroy`."
            )
