## ------------------------------------------------------------------------------------
## Negative tests for tower_container_version validation rules (variables.tf).
##
## Each `run` block overrides a single variable to an invalid value and asserts that
## the variable's validation trips at plan time. All other variables are sourced from
## tests/datafiles/terraform.tfvars — generated by `make generate_test_data` and
## passed in via `-var-file` (see `make terraform_test`).
##
## Floor + tag-shape rules being exercised:
##   - master supports only v26.1.0+ (see documentation/branching_policy.md)
##   - tag must match `^v\d+\.\d+\.\d+`
##
## A file-level `override_data` block stubs the external Python data source that
## generates the DB connection string, so the tests don't need a Docker daemon
## just to validate variables.
## ------------------------------------------------------------------------------------

mock_provider "aws" {}

# 000_main.tf jsondecodes each SSM payload and downstream locals look up specific
# keys (TOWER_DB_USER, SWELL_DB_USER, WAVE_LITE_REDIS_AUTH, etc.). Provide stub
# JSON per data source so plan can complete and the variable-validation diagnostics
# can surface. Keep this in sync with any new SSM key references in the .tf files.

override_data {
  target = data.aws_ssm_parameter.tower_secrets
  values = {
    value = "{\"TOWER_DB_USER\":{\"value\":\"stub\",\"ssm_key\":\"/stub/TOWER_DB_USER\"},\"TOWER_DB_PASSWORD\":{\"value\":\"stub\",\"ssm_key\":\"/stub/TOWER_DB_PASSWORD\"},\"TOWER_DB_MASTER_USER\":{\"value\":\"stub\",\"ssm_key\":\"/stub/TOWER_DB_MASTER_USER\"},\"TOWER_DB_MASTER_PASSWORD\":{\"value\":\"stub\",\"ssm_key\":\"/stub/TOWER_DB_MASTER_PASSWORD\"}}"
  }
}

override_data {
  target = data.aws_ssm_parameter.seqerakit_secrets
  values = {
    value = "{\"TOWER_AWS_ROLE\":{\"value\":\"stub\",\"ssm_key\":\"/stub/TOWER_AWS_ROLE\"}}"
  }
}

override_data {
  target = data.aws_ssm_parameter.groundswell_secrets
  values = {
    value = "{\"SWELL_DB_USER\":{\"value\":\"stub\",\"ssm_key\":\"/stub/SWELL_DB_USER\"},\"SWELL_DB_PASSWORD\":{\"value\":\"stub\",\"ssm_key\":\"/stub/SWELL_DB_PASSWORD\"}}"
  }
}

override_data {
  target = data.aws_ssm_parameter.wave_lite_secrets
  values = {
    value = "{\"WAVE_LITE_DB_MASTER_USER\":{\"value\":\"stub\",\"ssm_key\":\"/stub/WAVE_LITE_DB_MASTER_USER\"},\"WAVE_LITE_DB_MASTER_PASSWORD\":{\"value\":\"stub\",\"ssm_key\":\"/stub/WAVE_LITE_DB_MASTER_PASSWORD\"},\"WAVE_LITE_DB_LIMITED_USER\":{\"value\":\"stub\",\"ssm_key\":\"/stub/WAVE_LITE_DB_LIMITED_USER\"},\"WAVE_LITE_DB_LIMITED_PASSWORD\":{\"value\":\"stub\",\"ssm_key\":\"/stub/WAVE_LITE_DB_LIMITED_PASSWORD\"},\"WAVE_LITE_REDIS_AUTH\":{\"value\":\"stub\",\"ssm_key\":\"/stub/WAVE_LITE_REDIS_AUTH\"}}"
  }
}

override_data {
  target = module.connection_strings.data.external.generate_db_connection_string
  values = {
    result = {
      status = "0"
      value  = "?permitMysqlScheme=true"
    }
  }
}

run "rejects_v25_below_floor" {
  command = plan

  variables {
    tower_container_version = "v25.3.0"
  }

  expect_failures = [var.tower_container_version]
}

run "rejects_v23_below_floor" {
  command = plan

  variables {
    tower_container_version = "v23.4.5"
  }

  expect_failures = [var.tower_container_version]
}

run "rejects_missing_v_prefix" {
  command = plan

  variables {
    tower_container_version = "26.1.0"
  }

  expect_failures = [var.tower_container_version]
}

run "rejects_non_semver_tag" {
  command = plan

  variables {
    tower_container_version = "vlatest"
  }

  expect_failures = [var.tower_container_version]
}

run "accepts_v26_1_0" {
  command = plan

  variables {
    tower_container_version = "v26.1.0"
  }

  # No expect_failures — plan is expected to proceed past variable validation.
  # Other validations / cross-variable Python checks may still fail downstream;
  # this test only asserts the floor passes.
}
