## ------------------------------------------------------------------------------------
## Negative tests for tower_container_version validation rules (variables.tf).
##
## Each `run` block overrides a single variable to an invalid value and asserts that
## the variable's validation trips at plan time. All other variables are sourced from
## tests/datafiles/terraform.tfvars — generated by `make generate_test_data` and
## passed in via `-var-file` (see `make terraform_test`).
##
## Floor + tag-shape rules being exercised:
##   - master supports only v26.1.0+ (see documentation/branching_policy.md)
##   - tag must match `^v\d+\.\d+\.\d+`
##
## A file-level `override_data` block stubs the external Python data source that
## generates the DB connection string, so the tests don't need a Docker daemon
## just to validate variables.
## ------------------------------------------------------------------------------------

override_data {
  target = module.connection_strings.data.external.generate_db_connection_string
  values = {
    result = {
      status = "0"
      value  = "?permitMysqlScheme=true"
    }
  }
}

run "rejects_v25_below_floor" {
  command = plan

  variables {
    tower_container_version = "v25.3.0"
  }

  expect_failures = [var.tower_container_version]
}

run "rejects_v23_below_floor" {
  command = plan

  variables {
    tower_container_version = "v23.4.5"
  }

  expect_failures = [var.tower_container_version]
}

run "rejects_missing_v_prefix" {
  command = plan

  variables {
    tower_container_version = "26.1.0"
  }

  expect_failures = [var.tower_container_version]
}

run "rejects_non_semver_tag" {
  command = plan

  variables {
    tower_container_version = "vlatest"
  }

  expect_failures = [var.tower_container_version]
}

run "accepts_v26_1_0" {
  command = plan

  variables {
    tower_container_version = "v26.1.0"
  }

  # No expect_failures — plan is expected to proceed past variable validation.
  # Other validations / cross-variable Python checks may still fail downstream;
  # this test only asserts the floor passes.
}
