-- Postgres / gexec NEEDS single quotes in commands. Terraform tpl files strip them. This is a problem.
SELECT 'CREATE ROLE WAVEUSERREPLACEME LOGIN PASSWORD ''WAVEPASSWORDREPLACEME'''
WHERE NOT EXISTS (
  SELECT FROM pg_roles WHERE rolname = 'WAVEUSERREPLACEME'
)
\gexec

SELECT 'CREATE DATABASE wave'
WHERE NOT EXISTS (
  SELECT FROM pg_database WHERE datname = 'wave'
)
\gexec

GRANT ALL PRIVILEGES ON DATABASE wave TO WAVEUSERREPLACEME;


-- Connect to the wave DB first
\c wave

-- Grant usage and privileges on schemas/tables
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO WAVEUSERREPLACEME;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO WAVEUSERREPLACEME;
GRANT USAGE, CREATE ON SCHEMA public TO WAVEUSERREPLACEME;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL PRIVILEGES ON TABLES TO WAVEUSERREPLACEME;
